fail_fast: false
default_language_version:
    python: python3.10
repos:
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      language_version: python3.10
      files: (app|clients|tests)

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
    - id: reorder-python-imports
      files: (app|clients|tests)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
